# fly.toml app configuration file generated for phonebookistaken-wispy-dream-2115 on 2024-05-12T11:49:28+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebookistaken-wispy-dream-2115'
primary_region = 'ams'

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
